src/wadless/models/dashboard.py
from sqlalchemy.orm import synonym

from . import db, BaseModel, generate_uid


class Product(db.Model, BaseModel):
    __tablename__ = 'products'
    _uid = db.Column('uid', db.String(255))
    title = db.Column(db.String(255))
    url = db.Column(db.String(255))
    caption = db.Column(db.String(255))
    description = db.Column(db.Text)
    account_id = db.Column(db.Integer, db.ForeignKey('accounts.id', ondelete='CASCADE'))
    variants = db.relationship('Variant', backref='products')

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    @property
    def uid(self):
        return self._uid

    @uid.setter
    def uid(self, value: str):
        self._uid = value if value else f'product-{generate_uid()}'

    uid = synonym('_uid', descriptor=uid)  # https://bit.ly/2xsVGAF

    def __str__(self):
        return self.uid

    def __repr__(self):
        return '%s(%r)' % (self.__class__, self.__dict__)


class Variant(db.Model, BaseModel):
    __tablename__ = 'variants'
    title = db.Column(db.String(255))
    product_id = db.Column(db.Integer, db.ForeignKey('products.id', ondelete='CASCADE'))

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def __repr__(self):
        return '%s(%r)' % (self.__class__, self.__dict__)


class Inventory(db.Model, BaseModel):
    __tablename__ = 'inventories'
    _sku = db.Column('sku', db.String(255))
    price = db.Column(db.Integer)
    quantity = db.Column(db.Integer)
    is_active = db.Column(db.Boolean, default=False)
    variant_id = db.Column(db.Integer, db.ForeignKey('variants.id', ondelete='CASCADE'))
    menus = db.relationship('Listing', back_populates='inventory', passive_deletes=True)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    @property
    def sku(self):
        return self._sku

    @sku.setter
    def sku(self, value: str):
        self._sku = value if value else f'sku-{generate_uid()}'

    sku = synonym('_sku', descriptor=sku)  # https://bit.ly/2xsVGAF

    def __str__(self):
        return self.sku

    def __repr__(self):
        return '%s(%r)' % (self.__class__, self.__dict__)


class Listing(db.Model, BaseModel):
    __tablename__ = 'listings'
    inventory_id = db.Column(db.Integer, db.ForeignKey('inventories.id', ondelete='CASCADE'))
    menu_id = db.Column(db.Integer, db.ForeignKey('menus.id', ondelete='CASCADE'))
    inventory = db.relationship('Inventory', back_populates='menus')
    menu = db.relationship('Menu', back_populates='inventories')

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def __repr__(self):
        return '%s(%r)' % (self.__class__, self.__dict__)


class Menu(db.Model, BaseModel):
    __tablename__ = 'menus'
    title = db.Column(db.String(255))
    is_active = db.Column(db.Boolean, default=False)
    account_id = db.Column(db.Integer, db.ForeignKey('accounts.id', ondelete='CASCADE'))
    inventories = db.relationship('Listing', back_populates='menu')

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def __str__(self):
        return f'{self.id}'

    def __repr__(self):
        return '%s(%r)' % (self.__class__, self.__dict__)

src/wadless/views/dashboard.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, current_user

from src.wadless.models.dashboard import Product
from src.wadless.models.dashboard import Menu

dashboard_bp = Blueprint('dashboard', __name__)


@dashboard_bp.route('/dashboard')
@login_required
def index():
    menus = Menu.\
        query.\
        filter_by(account_id=current_user.account.id).\
        all()
    product = Product.\
        query.\
        filter_by(account_id=current_user.account.id).\
        first()
    context = {
        'product': product,
        'menus': menus
    }
    return render_template('dashboard/index.html', **context)

src/wadless/views/profile.py
from flask import Blueprint, render_template, flash
from flask_login import login_required, current_user

from src.wadless.models import db
from src.wadless.models.auth import User
from src.wadless.forms import EditEmailForm, EditNameForm, EditPasswordForm
from src.wadless.helpers.email import (
    email_change_email,
    email_change_password_success
)
from src.wadless.helpers.flash import flash_form_errors


profile_bp = Blueprint('profile', __name__)


def email_edit(form_email: EditEmailForm) -> None:
    """Send change of email to user.

    :param form_email: For for editing email
    :return: None
    """
    if form_email.validate_on_submit():
        old_email = current_user.email
        new_email = form_email.email.data

        if new_email == old_email:
            flash('New email should be different from old email', 'danger')
        else:
            user = User.query.filter_by(email=new_email).first()
            if user:
                flash('Email is already taken', 'danger')
            else:
                email_change_email(new_email)
                message = "To finish changing your email address, " \
                    f"we've sent an email to {new_email}. " \
                          "Simply click the button in the email to " \
                          "complete the process."
                flash(message, 'success')
    else:
        flash_form_errors(form_email.errors)


def name_edit(form_name: EditNameForm) -> None:
    """Assign new name to current user if valid

    :param form_name: Form for editing name
    :return: None
    """
    old_name = current_user.profile.name

    if form_name.validate_on_submit():
        new_name = form_name.name.data
        if new_name == old_name:
            flash('New name should be different from old name', 'danger')
        elif new_name:
            current_user.profile.name = new_name
            db.session.add(current_user)
            db.session.commit()
            flash('Successfully changed your profile name', 'success')
        else:
            flash('Please provide a valid name', 'danger')
    else:
        flash_form_errors(form_name.errors)


def password_edit(form_password: EditPasswordForm) -> None:
    """Send change of password to old email of user and assign new password.

    :param form_password: Form for editing password
    :return: None
    """
    if form_password.validate_on_submit():
        old_password = form_password.old_password.data
        new_password = form_password.new_password.data

        if old_password == new_password:
            flash('New password must be different from old password', 'danger')
        elif current_user.password_match(old_password):
            hashed_password = current_user.password_hash(new_password)
            current_user.password = hashed_password.decode('utf8')
            db.session.add(current_user)
            db.session.commit()
            email_change_password_success()
            flash('Successfully changed your password', 'success')
        else:
            flash('Wrong old password', 'danger')
    else:
        flash_form_errors(form_password.errors)


@profile_bp.route('/profile', methods=['GET', 'POST'])
@login_required
def index():
    form_email = EditEmailForm(prefix='form_email')
    form_name = EditNameForm(prefix='form_name')
    form_password = EditPasswordForm(prefix='form_password')

    if form_email.submit.data:
        email_edit(form_email)
    elif form_name.submit.data:
        name_edit(form_name)
    elif form_password.submit.data:
        password_edit(form_password)

    form_email.email.data = None
    form_name.name.data = None
    form_password.old_password.data = None
    form_password.new_password.data = None

    forms = {
        'form_email': form_email,
        'form_name': form_name,
        'form_password': form_password
    }
    return render_template('profile/index.html', **forms)

src/wadless/templates/dashboard/index.html
{% extends 'dashboard/layout.html' %}
{% block content %}

{% if not menus %}
    <div class='text-center'>
        <h5 class="font__custom--title mb-3">Let's get your store setup!</h5>
        <a class='btn btn__custom--primary mb-3' href="{{ url_for('product.create') }}">Create your first product</a>
        <br/>
        <a class='btn btn__custom--primary' href="{{ url_for('menu.create') }}">Setup your first menu</a>
    </div>
{% else %}
    <div class="card mb-3">
        <div class="card-body">
            <h3>Analytics</h3>
            <img src='https://placeholder.pics/svg/1400x100' class='img-fluid'>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <h3>Reports</h3>
            <img src='https://placeholder.pics/svg/1400x100' class='img-fluid'>
        </div>
    </div>
{% endif %}


{% endblock %}

src/wadless/templates/dashboard/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "shared/head.html" %} 
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/dashboard.css') }}"/>
</head>
<body>
    {% include "dashboard/nav.html" %}
    {% include "shared/messages.html" %}
    <div class='container container__padding'>
        {% block content %}{% endblock %}
    </div>
    {% include "shared/scripts.html" %}
</body>
</html>

src/wadless/templates/dashboard/nav.html
<nav class="navbar navbar-expand-lg navbar-light">
    <div class='container mb-2 mt-2'>
        {% include 'shared/brand.html' %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-nav-alt-markup" aria-controls="navbar-nav-alt-markup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar-nav-alt-markup">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item {% if request.url_rule.rule == '/dashboard' %} active {% endif %}"><a class="nav-link nav__navlink--center" href="{{ url_for('dashboard.index') }}"><i class='fas fa-home'></i> Home</a></li>
                <li class="nav-item {% if request.blueprint == 'inventory' %} active {% endif %}"><a class="nav-link nav__navlink--center" href="{{ url_for('inventory.index') }}"><i class='fas fa-list-alt'></i> Menus</a></li>
                <li class="nav-item {% if request.blueprint == 'product' %} active {% endif %}"><a class="nav-link nav__navlink--center" href="{{ url_for('product.index') }}"><i class='fas fa-cube'></i> Products</a></li>
                <li class="nav-item {% if request.blueprint == 'menu' %} active {% endif %}"><a class="nav-link nav__navlink--center" href="{{ url_for('menu.index') }}"><i class='fas fa-star'></i> Rewards</a></li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item mr-3"><a class="nav-link nav__navlink--center"><i class="fas fa-bell nav__usercircle--light"></i></a></li>
                <li class="nav-item mr-3"><a class="nav-link nav__navlink--center" href="mailto:john@wadless.com"><i class="fas fa-question-circle nav__usercircle--light"></i></a></li>
                <li class="nav-item mt-2">
                    <div class="dropdown">
                        <i class="far fa-user-circle nav__usercircle--{% if request.blueprint == 'profile'%}theme{%else%}light{%endif%}" data-toggle="dropdown"></i>
                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-tip-ne">
                            <h6 class="dropdown-header">{{ current_user.profile.name }}</h6>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item " href="{{ url_for('profile.index') }}">Profile</a>
                            <a class="dropdown-item " href="{{ url_for('auth.logout') }}">Logout</a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

src/wadless/templates/profile/index.html
{% extends 'merchant/layout.html' %}
{% from "form/horizontal.html" import render_field %}
{% block content %}

<div class="modal" id="change-name-modal" tabindex="-1" role="dialog" aria-labelledby="change-name-modal-title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="change-name-modal-title">Change name</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <form method="post">
                {{ form_name.csrf_token }}
                <div class="modal-body mt-3">
                    {{ render_field(form_name.name) }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn__custom--primary--outline" data-dismiss="modal">Cancel</button>
                    {{ form_name.submit(class_='btn btn__custom--primary') }}
                </div>
            </form>
        </div>
    </div>
</div>


<div class="modal" id="change-email-modal" tabindex="-1" role="dialog" aria-labelledby="change-email-modal-title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="change-email-modal-title">Change email</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <form method="post">
                {{ form_email.csrf_token }}
                <div class="modal-body mt-3">
                    {{ render_field(form_email.email) }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn__custom--primary--outline" data-dismiss="modal">Cancel</button>
                    {{ form_email.submit(class_='btn btn__custom--primary') }}
                </div>
            </form>
        </div>
    </div>
</div>


<div class="modal" id="change-password-modal" tabindex="-1" role="dialog"
     aria-labelledby="change-password-modal-title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="change-password-modal-title">Change password</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <form method="post">
                {{ form_password.csrf_token }}
                <div class="modal-body mt-3">
                    {{ render_field(form_password.old_password) }}
                    {{ render_field(form_password.new_password) }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn__custom--primary--outline" data-dismiss="modal">Cancel</button>
                    {{ form_password.submit(class_='btn btn__custom--primary') }}
                </div>
            </form>
        </div>
    </div>
</div>


<div class='row'>
    <div class='col-lg-3'></div>
    <div class='col-lg-6'>
        <div class='card'>
            <div class='card-body'>
                <h3 class='font__custom--title mt-3 mb-5'>Profile</h3>
                <div class='form-group row'>
                    <small class="col-md-3 col-form-label text-md-right label__text--small">Email</small>
                    <div class="col-md-6">
                        <p class="font__custom--text mt-1">{{ current_user.email }}</p>
                    </div>
                    <div class="col-md-3">
                        <button type="button" class="btn btn__custom--primary" data-toggle="modal" data-target="#change-email-modal">Edit</button>
                    </div>
                </div>
                <div class='form-group row'>
                    <small class="col-md-3 col-form-label text-md-right label__text--small">Name</small>
                    <div class="col-md-6">
                        <p class="font__custom--text mt-1">{{ current_user.profile.name }}</p>
                    </div>
                    <div class="col-md-3">
                        <button type="button" class="btn btn__custom--primary" data-toggle="modal" data-target="#change-name-modal">Edit</button>
                    </div>
                </div>
                <div class='form-group row'>
                    <small class="col-md-3 col-form-label text-md-right label__text--small">Password</small>
                    <div class="col-md-6">
                        <button type="button" class="btn btn__custom--primary" data-toggle="modal" data-target="#change-password-modal">Change password</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class='col-lg-3'></div>
</div>


{% endblock %}